version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: pretium3test
    networks:
      - minha_rede
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: pretium3test
      DATABASE_USER: postgres
      DATABASE_PASSWORD: admin
    depends_on:
      - db
    networks:
      - minha_rede
    ports:
      - "8080:8080"

networks:
  minha_rede:
    driver: bridge
